---
- name: Create an ec2 instance build
  hosts: localhost
  gather_facts: false
 
  vars:
      region: us-east-2
      instance_type: t2.micro
      ami: ami-08962a4068733a2b6
      keypair: my-key
 
  tasks:
    - name: Create an ec2 instance
      ec2:
         key_name: "{{ keypair }}"
         group: EC2SecurityGroup1
         instance_type: "{{ instance_type }}"
         image: "{{ ami }}"
         wait: true
         region: "{{ region }}"
        exact_count: 2
         count_tag:
            Name: Demo
         instance_tags:
            Name: Demo
         assign_public_ip: yes
      register: ec2