---
- name: Create an ec2 instance build
  hosts: localhost
  gather_facts: false
  
  vars:
      region: us-east-2
      instance_type: t2.micro
      ami: ami-08962a4068733a2b6
      keypair: my-key
 
  tasks:
    - name: Create an ec2 instance
      ec2:
         # key_name: "{{ keypair }}"
         group: EC2SecurityGroup1
         instance_type: "{{ instance_type }}"
         image: "{{ ami }}"
         wait: true
         region: "{{ region }}"
         vpc_subnet_id: subnet-79d39435       
         instance_tags:
           Name: "{{ item }}"
         count_tag:
           Name: "{{ item }}"
         exact_count: 1
         assign_public_ip: yes
      with_items: ['build', 'prod']
      register: ec2